Support kernel 5.3.0+
Add -mfentry CFLAG, which resolves
    ERROR: "mcount" [gspca-kinect2/gspca_main.ko] undefined!
on kernels 5.3.0 (occurred on Ubuntu 5.3.0-53-lowlatency).

Tested also on default Ubuntu bionic kernel 4.15.0 (which
wouldn't need the flag) and it still works, so it doesn't
seem to break on older kernels either.